### ISSUE TITLE
Won't read GOOGLE_APPLICATION_CREDENTIALS despite being present

### ISSUE THREAD

**Issue by 7Hazard** [GoogleCloudPlatform/artifact-registry-npm-tools#49]
I am trying to run `npx google-artifactregistry-auth` to publish to a GAR repo. Authentication, terraform and everything else pretty much works but the tool refuses to acknowledge `GOOGLE_APPLICATION_CREDENTIALS` despite it being set for the step.
These are the logs of the step from the GitHub workflow
```
Run npx google-artifactregistry-auth
  npx google-artifactregistry-auth
  shell: /usr/bin/bash -e {0}
  env:
    GOOGLE_APPLICATION_CREDENTIALS: /runner/_work/_temp/800a3c4b58ce99059c69334d
npm WARN exec The following package was not found and will be installed: google-artifactregistry-auth@3.1.0
Retrieving application default credentials...
Retrieving credentials from gcloud...
Error: Fail to get credentials. Please run: 
`gcloud auth application-default login`, `gcloud auth login`, or 
`export GOOGLE_APPLICATION_CREDENTIALS=<path/to/service/account/key>`
    at Object.getCreds (/home/runner/.npm/_npx/64aef35f3ba01c[7](https://github.sebank.se/hephaestus/verification/runs/964560?check_suite_focus=true#step:6:8)c/node_modules/google-artifactregistry-auth/src/auth.js:40:9)
    at async main (/home/runner/.npm/_npx/64aef35f3ba01c7c/node_modules/google-artifactregistry-auth/src/main.js:[8](https://github.sebank.se/hephaestus/verification/runs/964560?check_suite_focus=true#step:6:9)3:1[9](https://github.sebank.se/hephaestus/verification/runs/964560?check_suite_focus=true#step:6:10))
Error: Process completed with exit code 1.
```

**Comment by yihanzhen** [comment]
It looks like the `GOOGLE_APPLICATION_CREDENTIALS` environment variable has the wrong value. It should be set to a path to the service account key json file, but here it's set to `/runner/_work/_temp/800a` which is probably not the json key?

**Comment by 7Hazard** [comment]
Something weird happened when I copied, the actual value to the variable is `/runner/_work/_temp/800a3c4b58ce99059c69334d`

**Comment by yihanzhen** [comment]
Thanks @7Hazard . I must admit I am not very familiar with workload identity federation, although looking at https://github.com/googleapis/google-auth-library-nodejs/releases/tag/v7.0.0 the workload identity credentials config file should be supported out of the box, and we are indeed using google-auth-library-nodejs >7.0.0 (https://github.com/GoogleCloudPlatform/artifact-registry-npm-tools/blob/master/package.json#L10)

Would you mind running `npx google-artifactregistry-auth --verbose` so that we can see why the auth library couldn't retrieve ADC?

**Comment by 7Hazard** [comment]
So at first, without setting up gcloud before:
```
npm WARN exec The following package was not found and will be installed: google-artifactregistry-auth@3.1.0
Retrieving application default credentials...
Failed to retrieve application default credentials: client.getTokenInfo is not a function. Fall back to gcloud credentials.
Retrieving credentials from gcloud...
Failed to retrieve credentials from gcloud: Command failed: gcloud auth print-access-token
/bin/sh: 1: gcloud: not found
.
Error: Fail to get credentials. Please run: 
`gcloud auth application-default login`, `gcloud auth login`, or 
`export GOOGLE_APPLICATION_CREDENTIALS=<path/to/service/account/key>`
    at Object.getCreds (/home/runner/.npm/_npx/64aef35f3ba01c7c/node_modules/google-artifactregistry-auth/src/auth.js:40:9)
    at async main (/home/runner/.npm/_npx/64aef35f3ba01c7c/node_modules/google-artifactregistry-auth/src/main.js:83:19)
Error: Process completed with exit code 1.
```
With gcloud set up:
```
npm WARN exec The following package was not found and will be installed: google-artifactregistry-auth@3.1.0
Retrieving application default credentials...
Failed to retrieve application default credentials: Error code invalid_grant: The issuer in ID Token https://github.company.com/_services/token does not match the expected ones: https://spiffe.company.com.. Fall back to gcloud credentials.
Retrieving credentials from gcloud...
Failed to retrieve credentials from gcloud: Command failed: gcloud auth print-access-token
ERROR: (gcloud.auth.print-access-token) ('Error code invalid_grant: The issuer in ID Token https://github.company.com/_services/token does not match the expected ones: https://spiffe.company.com.', '{"error":"invalid_grant","error_description":"The issuer in ID Token https://github.company.com/_services/token does not match the expected ones: https://spiffe.company.com."}')
.
Error: Fail to get credentials. Please run: 
`gcloud auth application-default login`, `gcloud auth login`, or 
`export GOOGLE_APPLICATION_CREDENTIALS=<path/to/service/account/key>`
    at Object.getCreds (/home/runner/.npm/_npx/64aef35f3ba01c7c/node_modules/google-artifactregistry-auth/src/auth.js:40:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/runner/.npm/_npx/64aef35f3ba01c7c/node_modules/google-artifactregistry-auth/src/main.js:83:19)
Error: Process completed with exit code 1.
```

Seeing the second error, it does make me think that something might be wrong with our company's set up of SPIFFE. I'll forward this internally to those who manage this.

**Comment by yihanzhen** [comment]
@GusPrice looking at the error:
```
The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource..
```

This looks like some system access issue within your docker image and the user cannot open the service account key file?

**Comment by yihanzhen** [comment]
@7Hazard Is the issue still here?

**Comment by GusPrice** [comment]
@yihanzhen, sorry looks like I sent you the logs from a local test where I was trying to replicate. Here is a log from Github:
```
#20 0.504 > npx google-artifactregistry-auth --verbose
#20 0.504 
#20 1.286 npm WARN exec The following package was not found and will be installed: google-artifactregistry-auth@3.1.0
#20 3.277 Retrieving application default credentials...
#20 3.827 Failed to retrieve application default credentials: client.getTokenInfo is not a function. Fall back to gcloud credentials.
#20 3.828 Retrieving credentials from gcloud...
#20 3.833 Failed to retrieve credentials from gcloud: Command failed: gcloud auth print-access-token
#20 3.833 /bin/sh: gcloud: not found
#20 3.833 .
#20 3.835 Error: Fail to get credentials. Please run: 
#20 3.835 `gcloud auth application-default login`, `gcloud auth login`, or 
#20 3.835 `export GOOGLE_APPLICATION_CREDENTIALS=<path/to/service/account/key>`
#20 3.835     at Object.getCreds (/root/.npm/_npx/64aef35f3ba01c7c/node_modules/google-artifactregistry-auth/src/auth.js:40:9)
#20 3.835     at async main (/root/.npm/_npx/64aef35f3ba01c7c/node_modules/google-artifactregistry-auth/src/main.js:83:19)
#20 3.854 npm notice 
#20 3.854 npm notice New major version of npm available! 8.15.0 -> 9.6.2
#20 3.855 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.2>
#20 3.855 npm notice Run `npm install -g npm@9.6.2` to update!
#20 3.855 npm notice 
```

Looks like even with the verbose option there isn't much difference in this output.

**Comment by GusPrice** [comment]
Here's an interesting update (happy to open my own issue if you'd prefer), a similar set of steps, with the same credentials file works outside of docker. My Github action, which runs succesfully, for our unit tests looks like:

```
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/<project_id>/locations/global/workloadIdentityPools/github-pool/providers/github-pool-provider
        service_account: github-actions@<project_id>.iam.gserviceaccount.com
        create_credentials_file: true

    - name: Prep NPM Mirror
      shell: bash
      run: |
        npm run artifactregistry-login
```

The GitHub Action where it doesn't work:

```
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/<project_id>/locations/global/workloadIdentityPools/github-pool/providers/github-pool-provider
        service_account: github-actions@<project_id>iam.gserviceaccount.com
        create_credentials_file: true
        
   - name: Build and Push Image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ inputs.push }}
        tags: ${{ env.IMAGE_TAGS }}
        file: ${{ inputs.dockerfile }}
        secret-files: creds=${{ env.GOOGLE_APPLICATION_CREDENTIALS }} #this should come from the auth step
```
along with Dockerfile contents I shared previously:
```
FROM node:16.17.1-alpine3.16 as frontendpackages
# create node_modules layer for optimal caching
WORKDIR /frontend
COPY ./frontend/package.json .
COPY ./frontend/package-lock.json .
COPY ./frontend/.npmrc .npmrc
ENV GOOGLE_APPLICATION_CREDENTIALS=./application_default_credentials.json      
RUN --mount=type=secret,id=creds,target=./application_default_credentials.json \
    npm run artifactregistry-login && \
    npm ci --no-optional
```

**Comment by GusPrice** [comment]
@yihanzhen I see you closed this issue, will it be possible to publish a new version with your patch?

**Comment by yihanzhen** [comment]
Here you go: https://github.com/GoogleCloudPlatform/artifact-registry-npm-tools/pull/51

**Comment by az-oolloow** [comment]
This still seems to be an issue, unfortunately even with version 3.1.1

**Comment by yihanzhen** [comment]
@az-oolloow would you mind create a separate issue with the error you are seeing?

**Comment by az-oolloow** [comment]
@yihanzhen I did so here: https://github.com/GoogleCloudPlatform/artifact-registry-npm-tools/issues/53
