### ISSUE TITLE
Google Application Default Credentials during local docker build

### ISSUE THREAD

**Issue by az-oolloow** [GoogleCloudPlatform/artifact-registry-npm-tools#53]
I have a Docker image of a javascript application that uses private npm packages stored in Google's Artifact Registry.

Inside Google's CloudBuild I can specify `docker build -t myimage --network=cloudbuild .` and inside the docker build I can run `npx google-artifactregistry-auth` which retrieves the credentials using the build service account and then I can run my RUN `npm install`.

However, locally when I have ADC on my computer (macOS), setup by running `gcloud auth application-default login`, running the same command in docker fails saying:

```
#19 2.583 npm WARN exec The following package was not found and will be installed: google-artifactregistry-auth@3.1.1
#19 6.822 Retrieving application default credentials...
#19 6.846 Retrieving credentials from gcloud...
#19 6.856 Error: Fail to get credentials. Please run:
#19 6.856 gcloud auth application-default login, gcloud auth login, or
#19 6.856 export GOOGLE_APPLICATION_CREDENTIALS=<path/to/service/account/key>
#19 6.856 at Object.getCreds (/root/.npm/_npx/64aef35f3ba01c7c/node_modules/google-artifactregistry-auth/src/auth.js:40:9)
#19 6.856 at async main (/root/.npm/_npx/64aef35f3ba01c7c/node_modules/google-artifactregistry-auth/src/main.js:83:19)
```

Now I tried modifying my Dockerfile to do

```
RUN --mount=type=secret,id=creds export GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/creds && npm run artifactregistry-login
```

and then building like so:
```
docker build --secret id=creds,src=/Users/myUserName/.config/gcloud/application_default_credentials.json --progress=plain --no-cache -t hello-world .
```

I know (if I `cat` or `echo`) that my ADC is loaded correctly into the build process, but somehow I get the same `Fail to get credentials.` error.

**Comment by yihanzhen** [comment]
The `application_default_credentials.json` created by `gcloud application-default login` cannot be used as the service account json key referenced by the environment variable `GOOGLE_APPLICATION_CREDENTIALS` because they have different contents.

Here's what I think you can do (I must say I am not very familiar with docker runtime):
- mount `~/.config` of your machine to `/root/.config` inside the container, and make sure your docker image has gcloud installed. The `application_default_credentials.json` created by gcloud is only understandable by gcloud, so you will need to expose that to the docker container and let the gcloud inside the docker container do the authentication.

reference: https://stackoverflow.com/questions/38938216/pass-google-default-application-credentials-in-local-docker-run

**Comment by yihanzhen** [comment]
Closing due to inactivity. Feel free to ask for reopening if the issue is still here.
